name: lockfile-node20

on:
  workflow_dispatch:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20.19.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.x"

      - name: Versions
        run: |
          npm --version
          node --version

      - name: Generate package-lock.json
        run: |
          npm ci --no-audit --no-fund || npm install --package-lock-only --no-audit --no-fund --ignore-scripts

      - name: Create diff artifact
        run: |
          git diff -- package-lock.json > patch-y-package-lock.diff

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: patch-y-package-lock
          path: |
            package-lock.json
            patch-y-package-lock.diff
